-- BakerBake Daily Inventory Log feature.
-- Run after the POS normalization migrations.

create table if not exists public.inventory_units (
  id bigint generated by default as identity primary key,
  code text not null unique,
  label text not null,
  allow_decimal boolean not null default true,
  sort_order integer not null default 0
);

create table if not exists public.inventory_categories (
  id bigint generated by default as identity primary key,
  name text not null unique,
  sort_order integer not null default 0,
  active boolean not null default true
);

create table if not exists public.inventory_items (
  id bigint generated by default as identity primary key,
  category_id bigint not null references public.inventory_categories(id) on delete cascade,
  name text not null,
  default_unit_id bigint not null references public.inventory_units(id),
  sort_order integer not null default 0,
  active boolean not null default true,
  unique (category_id, name)
);

create table if not exists public.inventory_logs (
  id bigint generated by default as identity primary key,
  log_date date not null,
  status text not null default 'draft' check (status in ('draft', 'submitted', 'voided', 'corrected')),
  submitted_by text,
  submitted_at timestamptz,
  created_by text,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  unique (log_date)
);

create table if not exists public.inventory_log_lines (
  id bigint generated by default as identity primary key,
  inventory_log_id bigint not null references public.inventory_logs(id) on delete cascade,
  category_id bigint not null references public.inventory_categories(id),
  item_id bigint references public.inventory_items(id),
  custom_item_name text,
  unit_id bigint not null references public.inventory_units(id),
  in_qty numeric(14, 3) not null default 0,
  out_qty numeric(14, 3) not null default 0,
  remaining_qty numeric(14, 3) generated always as (in_qty - out_qty) stored,
  is_custom boolean not null default false,
  sort_order integer not null default 0,
  notes text,
  created_at timestamptz not null default now(),
  constraint inventory_line_item_name_check check (
    item_id is not null or nullif(custom_item_name, '') is not null
  ),
  constraint inventory_line_qty_check check (in_qty >= 0 and out_qty >= 0)
);

create table if not exists public.inventory_sheet_sync_jobs (
  id bigint generated by default as identity primary key,
  inventory_log_id bigint not null references public.inventory_logs(id) on delete cascade,
  status text not null default 'pending' check (status in ('pending', 'processing', 'completed', 'failed', 'skipped')),
  attempts integer not null default 0,
  last_error text,
  google_sheet_id text,
  synced_at timestamptz,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create index if not exists inventory_items_category_idx on public.inventory_items(category_id, sort_order);
create index if not exists inventory_log_lines_log_idx on public.inventory_log_lines(inventory_log_id, category_id, sort_order);
create index if not exists inventory_sheet_sync_jobs_status_idx on public.inventory_sheet_sync_jobs(status, created_at);

insert into public.inventory_units (code, label, allow_decimal, sort_order) values
  ('g', 'grams', true, 1),
  ('kg', 'kilograms', true, 2),
  ('kl', 'kilograms', true, 3),
  ('ml', 'milliliters', true, 4),
  ('pcs', 'pieces', false, 5),
  ('b', 'bottles', false, 6)
on conflict (code) do update set
  label = excluded.label,
  allow_decimal = excluded.allow_decimal,
  sort_order = excluded.sort_order;

insert into public.inventory_categories (name, sort_order) values
  ('Coffee Items', 1),
  ('Cookie - Dry Ingredients', 2),
  ('Cookie - Wet Ingredients', 3),
  ('Cookie - Mix-ins & Toppings', 4),
  ('Cookie - Packaging', 5)
on conflict (name) do update set sort_order = excluded.sort_order, active = true;

with seed(category_name, item_name, unit_code, sort_order) as (
  values
    ('Coffee Items', 'Coffee Bean', 'g', 1),
    ('Coffee Items', 'Milk', 'pcs', 2),
    ('Coffee Items', 'Condensed', 'ml', 3),
    ('Coffee Items', '8 oz. Craft Cup', 'pcs', 4),
    ('Coffee Items', '12 oz. Craft Cup', 'pcs', 5),
    ('Coffee Items', '8 oz. Craft Lid', 'pcs', 6),
    ('Coffee Items', '12 oz. Craft Lid', 'pcs', 7),
    ('Coffee Items', '12 oz. Plastic Cup', 'pcs', 8),
    ('Coffee Items', '16 oz. Plastic Cup', 'pcs', 9),
    ('Coffee Items', '12 oz. Plastic Lid', 'pcs', 10),
    ('Coffee Items', '16 oz. Plastic Lid', 'pcs', 11),
    ('Coffee Items', 'Single T.O. Plastic', 'pcs', 12),
    ('Coffee Items', 'Double T.O. Plastic', 'pcs', 13),
    ('Cookie - Dry Ingredients', 'APF', 'kg', 1),
    ('Cookie - Dry Ingredients', 'Baking Soda', 'g', 2),
    ('Cookie - Dry Ingredients', 'Baking Powder', 'g', 3),
    ('Cookie - Dry Ingredients', 'Salt', 'g', 4),
    ('Cookie - Dry Ingredients', 'Cocoa Powder', 'g', 5),
    ('Cookie - Dry Ingredients', 'Matcha Powder', 'g', 6),
    ('Cookie - Dry Ingredients', 'Brown Sugar', 'kg', 7),
    ('Cookie - Dry Ingredients', 'White Sugar', 'kg', 8),
    ('Cookie - Wet Ingredients', 'Eggs', 'pcs', 1),
    ('Cookie - Wet Ingredients', 'Butter', 'pcs', 2),
    ('Cookie - Wet Ingredients', 'Vanilla', 'ml', 3),
    ('Cookie - Wet Ingredients', 'Biscoff Spread', 'g', 4),
    ('Cookie - Wet Ingredients', 'Green Food Coloring', 'b', 5),
    ('Cookie - Wet Ingredients', 'Red Food Coloring', 'b', 6),
    ('Cookie - Wet Ingredients', 'Shortening', 'kg', 7),
    ('Cookie - Mix-ins & Toppings', 'Biscoff Biscuit', 'g', 1),
    ('Cookie - Mix-ins & Toppings', 'Biscoff Crumbs', 'g', 2),
    ('Cookie - Mix-ins & Toppings', 'D.B.S Chocolate', 'kg', 3),
    ('Cookie - Mix-ins & Toppings', 'White Chocolate', 'kg', 4),
    ('Cookie - Mix-ins & Toppings', 'Cashews', 'g', 5),
    ('Cookie - Packaging', 'Craft Box Packaging', 'pcs', 1),
    ('Cookie - Packaging', 'Individual Plastic Packaging', 'pcs', 2),
    ('Cookie - Packaging', 'Takeout Paper Bag', 'pcs', 3)
)
insert into public.inventory_items (category_id, name, default_unit_id, sort_order)
select categories.id, seed.item_name, units.id, seed.sort_order
from seed
join public.inventory_categories categories on categories.name = seed.category_name
join public.inventory_units units on units.code = seed.unit_code
on conflict (category_id, name) do update set
  default_unit_id = excluded.default_unit_id,
  sort_order = excluded.sort_order,
  active = true;

alter table public.inventory_units enable row level security;
alter table public.inventory_categories enable row level security;
alter table public.inventory_items enable row level security;
alter table public.inventory_logs enable row level security;
alter table public.inventory_log_lines enable row level security;
alter table public.inventory_sheet_sync_jobs enable row level security;

drop policy if exists "pos realtime inventory logs" on public.inventory_logs;
create policy "pos realtime inventory logs" on public.inventory_logs for select to authenticated using (true);
drop policy if exists "pos realtime inventory lines" on public.inventory_log_lines;
create policy "pos realtime inventory lines" on public.inventory_log_lines for select to authenticated using (true);

do $$
begin
  alter publication supabase_realtime add table public.inventory_logs;
exception when duplicate_object then null;
end $$;
do $$
begin
  alter publication supabase_realtime add table public.inventory_log_lines;
exception when duplicate_object then null;
end $$;

notify pgrst, 'reload schema';
