-- BakerBake POS normalized data migration.
-- Safe to run more than once. Existing orders and product catalog data are preserved.

create extension if not exists pgcrypto;

alter table public.orders add column if not exists request_id text;
alter table public.orders add column if not exists previous_status text;
alter table public.orders add column if not exists previously_completed boolean not null default false;
alter table public.orders add column if not exists last_completed_at timestamptz;
alter table public.orders add column if not exists void_reason text;
alter table public.orders add column if not exists voided_at timestamptz;
alter table public.orders add column if not exists voided_by text;
alter table public.orders add column if not exists authorized_by text;
create unique index if not exists orders_request_id_idx
  on public.orders(request_id) where request_id is not null;

create table if not exists public.products (
  id bigint primary key,
  name text not null,
  category text not null check (category in ('HOT', 'COLD', 'PASTRY')),
  subgroup text,
  image_url text,
  active boolean not null default true,
  sort_order integer not null default 0,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create table if not exists public.product_variants (
  id bigint generated by default as identity primary key,
  product_id bigint not null references public.products(id) on delete cascade,
  variant_key text not null,
  label text not null,
  price numeric(12, 2) not null check (price >= 0),
  sort_order integer not null default 0,
  unique (product_id, variant_key)
);

create table if not exists public.order_items (
  id bigint generated by default as identity primary key,
  order_id bigint not null references public.orders(id) on delete cascade,
  product_id bigint references public.products(id) on delete set null,
  product_name text not null,
  variant_key text,
  size_label text,
  quantity integer not null check (quantity > 0),
  unit_price numeric(12, 2) not null check (unit_price >= 0),
  created_at timestamptz not null default now()
);

create table if not exists public.void_requests (
  id uuid primary key default gen_random_uuid(),
  order_id bigint not null references public.orders(id) on delete cascade,
  status text not null default 'pending' check (status in ('pending', 'approved', 'rejected')),
  reason text not null,
  requested_by text not null,
  requested_at timestamptz not null default now(),
  reviewed_by text,
  reviewed_at timestamptz
);

create table if not exists public.pos_users (
  username text primary key,
  name text not null,
  role text not null check (role in ('cashier', 'admin')),
  password_hash text not null,
  active boolean not null default true,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create table if not exists public.audit_logs (
  id bigint generated by default as identity primary key,
  actor_username text,
  actor_role text,
  action text not null,
  entity_type text not null,
  entity_id text,
  details jsonb not null default '{}'::jsonb,
  created_at timestamptz not null default now()
);

create index if not exists products_category_idx on public.products(category, active);
create index if not exists order_items_order_id_idx on public.order_items(order_id);
create index if not exists void_requests_order_id_idx on public.void_requests(order_id);
create index if not exists void_requests_status_idx on public.void_requests(status, requested_at desc);
create unique index if not exists void_requests_one_pending_idx
  on public.void_requests(order_id) where status = 'pending';
create index if not exists audit_logs_created_at_idx on public.audit_logs(created_at desc);

-- Backfill products from the legacy app_state catalog.
insert into public.products (id, name, category, subgroup, image_url, active, sort_order)
select
  (item->>'id')::bigint,
  item->>'name',
  coalesce(item->>'filter', 'PASTRY'),
  nullif(item->>'subgroup', ''),
  item->>'imageUrl',
  coalesce((item->>'active')::boolean, true),
  ordinal::integer
from public.app_state state,
     jsonb_array_elements(state.value) with ordinality catalog(item, ordinal)
where state.key = 'product_catalog'
on conflict (id) do update set
  name = excluded.name,
  category = excluded.category,
  subgroup = excluded.subgroup,
  image_url = excluded.image_url,
  active = excluded.active,
  sort_order = excluded.sort_order,
  updated_at = now();

insert into public.product_variants (product_id, variant_key, label, price, sort_order)
select
  (item->>'id')::bigint,
  variant->>'id',
  coalesce(variant->>'label', variant->>'id'),
  (variant->>'price')::numeric,
  variant_ordinal::integer
from public.app_state state,
     jsonb_array_elements(state.value) catalog(item),
     jsonb_array_elements(coalesce(item->'variants', '[]'::jsonb))
       with ordinality variants(variant, variant_ordinal)
where state.key = 'product_catalog'
on conflict (product_id, variant_key) do update set
  label = excluded.label,
  price = excluded.price,
  sort_order = excluded.sort_order;

insert into public.product_variants (product_id, variant_key, label, price, sort_order)
select
  (item->>'id')::bigint,
  'single',
  'Single',
  (item->>'price')::numeric,
  0
from public.app_state state,
     jsonb_array_elements(state.value) catalog(item)
where state.key = 'product_catalog'
  and item ? 'price'
  and not (item ? 'variants')
on conflict (product_id, variant_key) do update set price = excluded.price;

update public.orders
set
  request_id = coalesce(request_id, nullif(payload->>'requestId', '')),
  previous_status = coalesce(previous_status, nullif(payload->>'previousStatus', '')),
  previously_completed = coalesce((payload->>'previouslyCompleted')::boolean, previously_completed),
  last_completed_at = coalesce(last_completed_at, nullif(payload->>'lastCompletedAt', '')::timestamptz),
  void_reason = coalesce(void_reason, nullif(payload->>'voidReason', '')),
  voided_at = coalesce(voided_at, nullif(payload->>'voidedAt', '')::timestamptz),
  voided_by = coalesce(voided_by, nullif(payload->>'voidedBy', '')),
  authorized_by = coalesce(authorized_by, nullif(payload->>'authorizedBy', ''));

-- Backfill order items from the legacy JSON column.
insert into public.order_items (
  order_id, product_id, product_name, variant_key, size_label, quantity, unit_price
)
select
  orders.id,
  nullif(item->>'productId', '')::bigint,
  coalesce(item->>'name', 'Unknown item'),
  nullif(item->>'variantId', ''),
  nullif(item->>'size', ''),
  greatest(coalesce((item->>'qty')::integer, 1), 1),
  greatest(coalesce((item->>'price')::numeric, 0), 0)
from public.orders,
     jsonb_array_elements(coalesce(orders.items, orders.payload->'items', '[]'::jsonb)) item
where not exists (
  select 1 from public.order_items existing where existing.order_id = orders.id
);

-- Backfill completed-order void requests from legacy payloads.
insert into public.void_requests (
  order_id, status, reason, requested_by, requested_at, reviewed_by, reviewed_at
)
select
  orders.id,
  coalesce(orders.payload->'voidRequest'->>'status', 'pending'),
  coalesce(orders.payload->'voidRequest'->>'reason', 'Legacy void request'),
  coalesce(orders.payload->'voidRequest'->>'requestedBy', orders.cashier),
  coalesce(nullif(orders.payload->'voidRequest'->>'requestedAt', '')::timestamptz, orders.updated_at),
  orders.payload->'voidRequest'->>'reviewedBy',
  nullif(orders.payload->'voidRequest'->>'reviewedAt', '')::timestamptz
from public.orders
where orders.payload ? 'voidRequest'
on conflict do nothing;

alter table public.products enable row level security;
alter table public.product_variants enable row level security;
alter table public.order_items enable row level security;
alter table public.void_requests enable row level security;
alter table public.pos_users enable row level security;
alter table public.audit_logs enable row level security;

drop policy if exists "pos realtime orders" on public.orders;
create policy "pos realtime orders" on public.orders for select to authenticated using (true);
drop policy if exists "pos realtime order items" on public.order_items;
create policy "pos realtime order items" on public.order_items for select to authenticated using (true);
drop policy if exists "pos realtime void requests" on public.void_requests;
create policy "pos realtime void requests" on public.void_requests for select to authenticated using (true);
drop policy if exists "pos realtime products" on public.products;
create policy "pos realtime products" on public.products for select to authenticated using (true);
drop policy if exists "pos realtime variants" on public.product_variants;
create policy "pos realtime variants" on public.product_variants for select to authenticated using (true);

do $$
begin
  alter publication supabase_realtime add table public.orders;
exception when duplicate_object then null;
end $$;
do $$
begin
  alter publication supabase_realtime add table public.order_items;
exception when duplicate_object then null;
end $$;
do $$
begin
  alter publication supabase_realtime add table public.void_requests;
exception when duplicate_object then null;
end $$;
do $$
begin
  alter publication supabase_realtime add table public.products;
exception when duplicate_object then null;
end $$;
do $$
begin
  alter publication supabase_realtime add table public.product_variants;
exception when duplicate_object then null;
end $$;
